version: '3.8'

services:
  # RabbitMQ Service
  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"   # RabbitMQ connection
      - "15672:15672" # Management console
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Ocelot Gateway
  charlie-gateway:
    image: tobbelito/charlie-gateway:latest
    container_name: charlie-gateway
    ports:
      - "5000:8080" # Map port 80 inside the container to 5000 on your host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq-service:
        condition: service_healthy
      customer-api:
        condition: service_started
      order-api:
        condition: service_started
      product-api:
        condition: service_started
      payment-service:
        condition: service_started
    networks:
      - app-network

  # Customer API
  customer-api:
    image: mrfigge/charlie-customer-api:latest
    container_name: customer-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq-service:
        condition: service_healthy
    networks:
      - app-network

  # Customer Service
  customer-service:
    image: mrfigge/charlie-customer:latest
    container_name: customer-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq-service:
        condition: service_healthy
    networks:
      - app-network

  # Order API
  order-api:
    image: antonmalm/charlie-order-api:latest
    container_name: order-api
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq-service:
        condition: service_healthy
    networks:
      - app-network

  # Order Service
  order-service:
    image: antonmalm/charlie-order:v20241217112114
    container_name: order-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq-service:
        condition: service_healthy
    networks:
      - app-network

  # Product API
  product-api:
    image: mrfrolin/charlie-product-api:latest
    container_name: product-api
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq-service:
        condition: service_healthy
    networks:
      - app-network

  # Product Service
  product-service:
    image: mrfrolin/charlie-product:latest
    container_name: product-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq-service:
        condition: service_healthy
    networks:
      - app-network

  # Payment Service
  payment-service:
    image: tobbelito/charlie-payment:latest
    container_name: payment-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq-service:
        condition: service_healthy
    networks:
      - app-network

# Network definition
networks:
  app-network:
    driver: bridge
